from __future__ import annotations
import json
from .ast import *
from .ir import lower


def _pyexpr(expr: str) -> str:
    return expr.replace("true", "True").replace("false", "False")


def generate_python(program: Program) -> str:
    air = lower(program)
    has_execute = any(isinstance(s, ExecuteStmt) for s in program.statements)
    out = [
        "# Generated by AegisAI compiler v0.4",
        "# Static information-flow, trust, capability, risk, placement and effect checks passed.",
        "# External effects are never performed implicitly; action.execute crosses an explicit runtime boundary.",
        "",
        "import json",
        "import os",
        "from pathlib import Path",
        "",
        f"AEGIS_AIR = {air!r}",
        "AEGIS_METADATA = {'capabilities': {}, 'models': {}, 'agents': {}, 'placements': {}, 'evidence': {}, 'proposals': {}, 'authorizations': [], 'actions': {}, 'tokens': {}, 'credentials': {}, 'adapters': {}, 'twin_connectors': {}, 'twins': {}, 'validations': [], 'executions': [], 'intents': {}, 'sequences': {}, 'transactions': {}}",
        "",
    ]
    for s in program.statements:
        if isinstance(s, DataDecl): out.append(f"{s.name} = {s.value!r}")
        elif isinstance(s, SecretDecl): out.append(f"{s.name} = {s.value!r}  # secret")
        elif isinstance(s, TaintedDecl): out.append(f"{s.name} = {s.value!r}  # tainted from {s.source}")
        elif isinstance(s, SanitizeStmt): out.append(f"{s.target} = {s.source}  # sanitized by AegisAI boundary")
        elif isinstance(s, EvidenceDecl): out.append(f"AEGIS_METADATA['evidence'][{s.name!r}] = {{'value': {s.value!r}, 'trust': {s.trust!r}, 'source': {s.source!r}}}")
        elif isinstance(s, PrintStmt): out.append(f"print({_pyexpr(s.expr)})")
        elif isinstance(s, RequireStmt): out.append(f"assert {_pyexpr(s.condition)}, 'AegisAI require failed'")
        elif isinstance(s, PolicyDecl): out.append(f"# policy {s.name}: " + " | ".join(s.rules))
        elif isinstance(s, CapabilityDecl): out.append(f"AEGIS_METADATA['capabilities'][{s.name!r}] = {{'effects': {sorted(s.effects)!r}, 'risk': {s.risk!r}}}")
        elif isinstance(s, ModelDecl): out.append(f"AEGIS_METADATA['models'][{s.name!r}] = {{'capabilities': {sorted(s.capabilities)!r}, 'trust': {s.trust!r}, 'network': {s.network!r}}}")
        elif isinstance(s, AgentDecl): out.append(f"AEGIS_METADATA['agents'][{s.name!r}] = {{'model': {s.model!r}, 'capabilities': {sorted(s.capabilities)!r}, 'deny': {sorted(s.denied)!r}, 'trust': {s.trust!r}}}")
        elif isinstance(s, PlacementDecl): out.append(f"AEGIS_METADATA['placements'][{s.target!r}] = {{'environment': {s.environment!r}, 'region': {s.region!r}, 'data_residency': {s.data_residency!r}, 'max_latency_ms': {s.max_latency_ms!r}, 'network': {s.network!r}}}")
        elif isinstance(s, ProposalDecl): out.append(f"AEGIS_METADATA['proposals'][{s.name!r}] = {{'agent': {s.agent!r}, 'risk': {s.risk!r}, 'capability': {s.capability!r}, 'effects': {sorted(s.effects)!r}, 'guards': {s.guards!r}, 'evidence': {s.evidence!r}, 'min_trust': {s.min_trust!r}, 'confidence': {s.confidence!r}}}")
        elif isinstance(s, AuthorizeStmt): out.append(f"AEGIS_METADATA['authorizations'].append(({s.proposal!r}, {s.policy!r}))")
        elif isinstance(s, ActionDecl): out.append(f"AEGIS_METADATA['actions'][{s.name!r}] = {{'proposal': {s.proposal!r}, 'capability': {s.capability!r}, 'effect': {s.effect!r}, 'reversible': {s.reversible!r}}}")
        elif isinstance(s, TokenDecl): out.append(f"AEGIS_METADATA['tokens'][{s.name!r}] = {{'agent': {s.agent!r}, 'capability': {s.capability!r}, 'ttl_seconds': {s.ttl_seconds!r}}}")
        elif isinstance(s, CredentialDecl): out.append(f"AEGIS_METADATA['credentials'][{s.name!r}] = {{'agent': {s.agent!r}, 'capability': {s.capability!r}, 'ttl_seconds': {s.ttl_seconds!r}, 'issuer': {s.issuer!r}}}")
        elif isinstance(s, AdapterDecl): out.append(f"AEGIS_METADATA['adapters'][{s.name!r}] = {{'effects': {sorted(s.effects)!r}, 'mode': {s.mode!r}, 'trust_zone': {s.trust_zone!r}}}")
        elif isinstance(s, TwinConnectorDecl): out.append(f"AEGIS_METADATA['twin_connectors'][{s.name!r}] = {{'transport': {s.transport!r}, 'endpoint': {s.endpoint!r}, 'timeout_ms': {s.timeout_ms!r}}}")
        elif isinstance(s, TwinDecl): out.append(f"AEGIS_METADATA['twins'][{s.name!r}] = {{'target': {s.target!r}, 'guards': {s.guards!r}, 'connector': {s.connector!r}}}")
        elif isinstance(s, TwinValidateStmt): out.append(f"AEGIS_METADATA['validations'].append(({s.action!r}, {s.twin!r}))")
        elif isinstance(s, ExecuteStmt): out.append(f"AEGIS_METADATA['executions'].append(({s.action!r}, {s.token!r}, {s.adapter!r}))")
        elif isinstance(s, IntentDecl): out.append(f"AEGIS_METADATA['intents'][{s.name!r}] = {{'objectives': {s.objectives!r}, 'constraints': {s.constraints!r}}}")
        elif isinstance(s, SequenceDecl): out.append(f"AEGIS_METADATA['sequences'][{s.name!r}] = {{'steps': {s.steps!r}}}")
        elif isinstance(s, SecureTransactionDecl): out.append(f"AEGIS_METADATA['transactions'][{s.name!r}] = {{'actions': {s.actions!r}, 'rollbacks': {s.rollbacks!r}}}")
        elif isinstance(s, FunctionDecl):
            out.append(f"def {s.name}({', '.join(s.params)}):")
            out.append(f"    # risk={s.risk}; effects={','.join(sorted(s.effects)) or 'none'}")
            if not s.body: out.append("    pass")
            for b in s.body:
                if isinstance(b, PrintStmt): out.append(f"    print({_pyexpr(b.expr)})")
                elif isinstance(b, RequireStmt): out.append(f"    assert {_pyexpr(b.condition)}, 'AegisAI require failed'")
                elif isinstance(b, CallStmt) and b.function == "__effect__": out.append(f"    # effect: {b.args[0]}")
        elif isinstance(s, CallStmt): out.append(f"{s.function}({', '.join(s.args)})")

    if has_execute:
        out.extend([
            "",
            "def _aegis_runtime_main():",
            "    from aegisai.runtime import run_air",
            "    from aegisai.credentials import SigningIdentity, load_private_key_pem",
            "    runtime_key = os.environ.get('AEGIS_RUNTIME_KEY')",
            "    context = json.loads(os.environ.get('AEGIS_RUNTIME_CONTEXT', '{}'))",
            "    signers = {}",
            "    cred_path = os.environ.get('AEGIS_CREDENTIAL_PRIVATE_KEY')",
            "    if cred_path:",
            "        issuer = os.environ.get('AEGIS_CREDENTIAL_ISSUER', 'AegisAI')",
            "        signers[issuer] = SigningIdentity(issuer, load_private_key_pem(Path(cred_path).read_bytes()))",
            "    result = run_air(AEGIS_AIR, context=context, runtime_key=runtime_key.encode('utf-8') if runtime_key else None, credential_signers=signers)",
            "    print(json.dumps(result.to_dict(), indent=2))",
            "",
            "if __name__ == '__main__':",
            "    _aegis_runtime_main()",
        ])
    out.append("")
    return "\n".join(out)
