from __future__ import annotations
from .ast import *


def _pyexpr(expr: str) -> str:
    return expr.replace("true", "True").replace("false", "False")


def generate_python(program: Program) -> str:
    out = [
        "# Generated by AegisAI compiler v0.2",
        "# Static security, trust, capability, risk and effect checks passed.",
        "",
        "AEGIS_METADATA = {'capabilities': {}, 'models': {}, 'agents': {}, 'evidence': {}, 'proposals': {}, 'authorizations': [], 'actions': {}, 'twins': {}, 'intents': {}, 'sequences': {}, 'transactions': {}}",
        "",
    ]
    for s in program.statements:
        if isinstance(s, DataDecl): out.append(f"{s.name} = {s.value!r}")
        elif isinstance(s, SecretDecl): out.append(f"{s.name} = {s.value!r}  # secret")
        elif isinstance(s, TaintedDecl): out.append(f"{s.name} = {s.value!r}  # tainted from {s.source}")
        elif isinstance(s, SanitizeStmt): out.append(f"{s.target} = {s.source}  # sanitized by AegisAI boundary")
        elif isinstance(s, EvidenceDecl): out.append(f"AEGIS_METADATA['evidence'][{s.name!r}] = {{'value': {s.value!r}, 'trust': {s.trust!r}, 'source': {s.source!r}}}")
        elif isinstance(s, PrintStmt): out.append(f"print({_pyexpr(s.expr)})")
        elif isinstance(s, RequireStmt): out.append(f"assert {_pyexpr(s.condition)}, 'AegisAI require failed'")
        elif isinstance(s, PolicyDecl): out.append(f"# policy {s.name}: " + " | ".join(s.rules))
        elif isinstance(s, CapabilityDecl): out.append(f"AEGIS_METADATA['capabilities'][{s.name!r}] = {{'effects': {sorted(s.effects)!r}, 'risk': {s.risk!r}}}")
        elif isinstance(s, ModelDecl): out.append(f"AEGIS_METADATA['models'][{s.name!r}] = {{'capabilities': {sorted(s.capabilities)!r}, 'trust': {s.trust!r}, 'network': {s.network!r}}}")
        elif isinstance(s, AgentDecl): out.append(f"AEGIS_METADATA['agents'][{s.name!r}] = {{'model': {s.model!r}, 'capabilities': {sorted(s.capabilities)!r}, 'deny': {sorted(s.denied)!r}, 'trust': {s.trust!r}}}")
        elif isinstance(s, ProposalDecl): out.append(f"AEGIS_METADATA['proposals'][{s.name!r}] = {{'agent': {s.agent!r}, 'risk': {s.risk!r}, 'capability': {s.capability!r}, 'effects': {sorted(s.effects)!r}, 'guards': {s.guards!r}, 'evidence': {s.evidence!r}, 'min_trust': {s.min_trust!r}}}")
        elif isinstance(s, AuthorizeStmt): out.append(f"AEGIS_METADATA['authorizations'].append(({s.proposal!r}, {s.policy!r}))")
        elif isinstance(s, ActionDecl): out.append(f"AEGIS_METADATA['actions'][{s.name!r}] = {{'proposal': {s.proposal!r}, 'capability': {s.capability!r}, 'effect': {s.effect!r}, 'reversible': {s.reversible!r}}}")
        elif isinstance(s, TwinDecl): out.append(f"AEGIS_METADATA['twins'][{s.name!r}] = {{'target': {s.target!r}, 'guards': {s.guards!r}}}")
        elif isinstance(s, IntentDecl): out.append(f"AEGIS_METADATA['intents'][{s.name!r}] = {{'objectives': {s.objectives!r}, 'constraints': {s.constraints!r}}}")
        elif isinstance(s, SequenceDecl): out.append(f"AEGIS_METADATA['sequences'][{s.name!r}] = {{'steps': {s.steps!r}}}")
        elif isinstance(s, SecureTransactionDecl): out.append(f"AEGIS_METADATA['transactions'][{s.name!r}] = {{'actions': {s.actions!r}, 'rollbacks': {s.rollbacks!r}}}")
        elif isinstance(s, FunctionDecl):
            out.append(f"def {s.name}({', '.join(s.params)}):")
            out.append(f"    # risk={s.risk}; effects={','.join(sorted(s.effects)) or 'none'}")
            if not s.body: out.append("    pass")
            for b in s.body:
                if isinstance(b, PrintStmt): out.append(f"    print({_pyexpr(b.expr)})")
                elif isinstance(b, RequireStmt): out.append(f"    assert {_pyexpr(b.condition)}, 'AegisAI require failed'")
                elif isinstance(b, CallStmt) and b.function == "__effect__": out.append(f"    # effect: {b.args[0]}")
        elif isinstance(s, CallStmt): out.append(f"{s.function}({', '.join(s.args)})")
    out.append("")
    return "\n".join(out)
