from __future__ import annotations
from .ast import *

def _pyexpr(expr: str) -> str:
    return expr.replace("true", "True").replace("false", "False")

def generate_python(program: Program) -> str:
    out = ["# Generated by AegisAI compiler", "# Security checks were performed before code generation.", ""]
    for s in program.statements:
        if isinstance(s, DataDecl):
            out.append(f"{s.name} = {s.value!r}")
        elif isinstance(s, SecretDecl):
            out.append(f"{s.name} = {s.value!r}  # secret")
        elif isinstance(s, PrintStmt):
            out.append(f"print({_pyexpr(s.expr)})")
        elif isinstance(s, RequireStmt):
            out.append(f"assert {_pyexpr(s.condition)}, 'AegisAI require failed'")
        elif isinstance(s, PolicyDecl):
            out.append(f"# policy {s.name}: " + " | ".join(s.rules))
        elif isinstance(s, FunctionDecl):
            out.append(f"def {s.name}({', '.join(s.params)}):")
            out.append(f"    # risk={s.risk}; effects={','.join(sorted(s.effects)) or 'none'}")
            if not s.body:
                out.append("    pass")
            for b in s.body:
                if isinstance(b, PrintStmt): out.append(f"    print({_pyexpr(b.expr)})")
                elif isinstance(b, RequireStmt): out.append(f"    assert {_pyexpr(b.condition)}, 'AegisAI require failed'")
                elif isinstance(b, CallStmt) and b.function == "__effect__": out.append(f"    # effect: {b.args[0]}")
        elif isinstance(s, CallStmt):
            out.append(f"{s.function}({', '.join(s.args)})")
    out.append("")
    return "\n".join(out)
